products = Product.create(category: "burgers", name: "Cheeseburger", description: "Bun, meat and cheese", price: 59 )
products = Product.create(category: "burgers", name: "Luger Burger", description: "features extra thick bacon and more than a half pound of beef.", price: 169 )
products = Product.create(category: "burgers", name: "Double Animal Style", description: "The Animal Style will give you added pickles, extra spread with grilled onions, and they’ll fry some mustard onto your patties.", price: 149 )
products = Product.create(category: "pizza", name: "Vesuvio", description: "By Janko with love", price: 700 )
products = Product.create(category: "pizza", name: "Valtellina", description: "For Romantic couples. Tomato sauce, mozzarella, bresaola, Parmesan flakes and rocket", price: 69 )
products = Product.create(category: "pizza", name: "Diavola", description: "Try this little devil! Tomato sauce, mozzarella, spicy salami, and chilli pepper", price: 66 )
users = User.create( email: "user@mail.com", password: "password", password_confirmation: "password" )